theme = 'hugo-theme-relearn'
baseURL = 'https://cegepmv.github.io/420-310'
languageCode = 'fr-fr'
title = 'Architecture Logicielle'

[params]
    collapsibleMenu = true
    disableLandingPageButton = true
    themeVariant = ['zen-light']
    disableInlineCopyToClipBoard = true
